app = "virtual-notifier"
primary_region = "ams" # you can choose "lhr", "cdg", "mad" etc. depending on your location

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "bet9ja_tracker.settings"
  PYTHONUNBUFFERED = "1"

[deploy]
  release_command = "python manage.py migrate"

[processes]
  web = "gunicorn bet9ja_tracker.wsgi:application --bind 0.0.0.0:8000"
  worker = "python manage.py run_tracker"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
