app = "virtual-notifier"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "bet9ja_tracker.settings"
  PYTHONUNBUFFERED = "1"

[deploy]
  release_command = "playwright install --with-deps chromium && python manage.py migrate"

[processes]
  web = "gunicorn bet9ja_tracker.wsgi:application --bind 0.0.0.0:8000"
  worker = "python manage.py run_tracker"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  process = "web"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[checks]
  [checks.http]
    type = "http"
    interval = 10000
    timeout = 2000
    method = "get"
    path = "/"
    protocol = "http"
    grace_period = "10s"
    restart_limit = 0
