# Generated by Django 5.1.4 on 2025-10-02 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AlterField(
            model_name='team',
            name='current_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.season'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
