# Generated by Django 5.1.4 on 2025-10-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_team_draws_team_losses_team_wins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={},
        ),
        migrations.RemoveField(
            model_name='league',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='league',
            name='offset',
        ),
        migrations.AddField(
            model_name='league',
            name='external_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
